#!/usr/bin/env bash
# =============================================================================
# infra/scripts/fix-auth0-vm3.sh
#
# CRITICAL FIX C1 — BUG-001: Enable Auth0 OIDC on VM3 (moderate-service)
#
# Run this script ONCE to inject real Auth0 credentials into VM3 and
# restart the moderate-service container.
#
# Usage:
#   1. Fill in the variables below with your real Auth0 values.
#   2. chmod +x infra/scripts/fix-auth0-vm3.sh
#   3. ./infra/scripts/fix-auth0-vm3.sh
#
# Prerequisites:
#   - SSH private key at ~/.ssh/co3404_key
#   - VM3 public IP known (check Terraform output or Azure portal)
#   - Auth0 "Regular Web Application" already created at https://manage.auth0.com
#   - In Auth0 Application Settings, set:
#       Allowed Callback URLs:  https://<KONG_PUBLIC_IP>/callback
#       Allowed Logout URLs:    https://<KONG_PUBLIC_IP>/moderate-ui
#       Allowed Web Origins:    https://<KONG_PUBLIC_IP>
# =============================================================================
set -euo pipefail

# ─── Fill in your values ──────────────────────────────────────────────────────
VM3_HOST=""                             # e.g. "52.163.x.x"  (VM3 public IP from Azure portal)
KONG_PUBLIC_IP=""                       # Kong VM public IP — run: terraform -chdir=infra/terraform output -raw kong_public_ip
DOCKER_IMAGE=""                         # e.g. "youruser/moderate-service:latest"
RABBITMQ_HOST="10.0.1.5"                        # VM2 private IP (default — matches Terraform config)
RABBITMQ_USER="REPLACE_WITH_RABBITMQ_USER"      # Must match RABBITMQ_USER set in infra/.env.vm2
RABBITMQ_PASSWORD="REPLACE_WITH_STRONG_RABBITMQ_PASSWORD"  # Must match RABBITMQ_PASSWORD in infra/.env.vm2

AUTH0_SECRET=""                         # Random 32+ char string (generate: openssl rand -hex 32)
AUTH0_CLIENT_ID=""                      # From Auth0 Application > Settings > Client ID
AUTH0_CLIENT_SECRET=""                  # From Auth0 Application > Settings > Client Secret
AUTH0_ISSUER_BASE_URL=""               # e.g. "https://your-tenant.auth0.com"
SSH_KEY="$HOME/.ssh/co3404_key"
# ─────────────────────────────────────────────────────────────────────────────

# Guard: check all required values are set (and none still have REPLACE_WITH_* placeholders)
for var in VM3_HOST KONG_PUBLIC_IP DOCKER_IMAGE AUTH0_SECRET AUTH0_CLIENT_ID AUTH0_CLIENT_SECRET AUTH0_ISSUER_BASE_URL RABBITMQ_USER RABBITMQ_PASSWORD; do
  if [[ -z "${!var}" ]] || [[ "${!var}" == REPLACE_WITH_* ]]; then
    echo "❌  ERROR: '$var' is not set (or still has a placeholder). Edit this script and fill in your values."
    exit 1
  fi
done

AUTH0_BASE_URL="https://${KONG_PUBLIC_IP}"

echo "🔐  Writing Auth0 .env to VM3 ($VM3_HOST)…"

# Write the .env file remotely via SSH heredoc
ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "azureuser@${VM3_HOST}" bash <<ENVSSH
set -e
mkdir -p /home/azureuser/moderate

cat > /home/azureuser/moderate/.env <<'EOF'
# Generated by fix-auth0-vm3.sh — do not edit manually

# ── Docker image ─────────────────────────────────────────────────────────────
DOCKER_IMAGE=${DOCKER_IMAGE}

# ── RabbitMQ (VM2 private IP) ─────────────────────────────────────────────
RABBITMQ_HOST=${RABBITMQ_HOST}
RABBITMQ_USER=${RABBITMQ_USER}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

# ── Auth0 OpenID Connect ──────────────────────────────────────────────────
# AUTH0_BASE_URL: The PUBLIC URL users browse to (through Kong).
# Must match Allowed Callback URLs in Auth0 dashboard (callback = baseURL + /callback).
AUTH0_SECRET=${AUTH0_SECRET}
AUTH0_BASE_URL=${AUTH0_BASE_URL}
AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}

# ── Port ──────────────────────────────────────────────────────────────────
PORT=4300
EOF

echo "✅  .env written to /home/azureuser/moderate/.env"
cat /home/azureuser/moderate/.env
ENVSSH

echo ""
echo "🔄  Restarting moderate-service container on VM3…"

ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "azureuser@${VM3_HOST}" bash <<RSTSSH
set -e
cd /home/azureuser/moderate

# Pull the latest image and recreate the container with new env vars
sudo docker compose pull moderate-service || true
sudo docker compose up -d --force-recreate moderate-service

echo ""
echo "⏳  Waiting 15s for service to start…"
sleep 15

# Health check
STATUS=\$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3300/health || echo "000")
echo "Health check: HTTP \$STATUS"

if [ "\$STATUS" = "200" ]; then
  echo "✅  moderate-service is healthy"
else
  echo "❌  Health check failed. Run: sudo docker compose -f /home/azureuser/moderate/vm3-compose.yml logs --tail=50"
  exit 1
fi
RSTSSH

echo ""
echo "🔍  Verifying Auth0 is now ENABLED (should return 302 redirect to Auth0, NOT 200)…"
HTTP=$(curl -sk -o /dev/null -w "%{http_code}" "https://${KONG_PUBLIC_IP}/moderate")
if [ "$HTTP" = "302" ] || [ "$HTTP" = "401" ]; then
  echo "✅  Auth0 is active. /moderate returned HTTP ${HTTP} (requires login)"
elif [ "$HTTP" = "200" ]; then
  echo "❌  FAIL: /moderate still returns 200 — Auth0 is NOT enforcing login."
  echo "    Check that AUTH0_CLIENT_ID is correct and not a placeholder."
  exit 1
else
  echo "ℹ️   /moderate returned HTTP ${HTTP} — verify manually"
fi

echo ""
echo "✅  Auth0 fix complete."
echo "    Test the moderation UI at: https://${KONG_PUBLIC_IP}/moderate-ui"
