#!/usr/bin/env bash
# =============================================================================
# infra/scripts/redeploy-kong.sh
#
# HIGH FIX C3 — BUG-002 / BUG-003:
#   1. Upload the current kong.yml (with rate-limit scope fix) to Kong VM
#   2. Reload Kong with zero-downtime config reload
#   3. Verify all routes respond correctly (including /etl-health and /joke-ui)
#
# Usage:
#   chmod +x infra/scripts/redeploy-kong.sh
#   ./infra/scripts/redeploy-kong.sh
#
# Prerequisites:
#   - SSH key at ~/.ssh/co3404_key
#   - Kong VM accessible (SSH port 22 open from your IP in NSG)
#   - infra/kong/kong.yml has been regenerated by terraform apply (or run this
#     script from the repo root after manually editing kong.yml directly)
# =============================================================================
set -euo pipefail

KONG_IP="${KONG_IP:-}"
SSH_KEY="$HOME/.ssh/co3404_key"
SSH_USER="azureuser"
KONG_YML_LOCAL="infra/kong/kong.yml"
REMOTE_KONG_DIR="/home/azureuser/kong"

if [ -z "$KONG_IP" ]; then
  echo "❌  ERROR: KONG_IP is not set."
  echo "    Usage: KONG_IP=<KONG_PUBLIC_IP> ./infra/scripts/redeploy-kong.sh"
  exit 1
fi

echo "📋  Pre-flight: Validating local kong.yml exists…"
if [ ! -f "$KONG_YML_LOCAL" ]; then
  echo "❌  ERROR: $KONG_YML_LOCAL not found. Run from the repo root."
  exit 1
fi

echo "📤  Uploading kong.yml to Kong VM ($KONG_IP)…"
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no \
  "$KONG_YML_LOCAL" \
  "${SSH_USER}@${KONG_IP}:${REMOTE_KONG_DIR}/kong.yml"

echo "✅  Uploaded. Reloading Kong (zero-downtime)…"

ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "${SSH_USER}@${KONG_IP}" bash <<'KONGSH'
set -e
cd /home/azureuser/kong

echo "── Current Kong container status ──"
sudo docker compose ps

echo ""
echo "── Reloading Kong config (zero-downtime via SIGHUP) ──"
# Kong 3.x: `kong reload` sends SIGHUP — no dropped connections.
sudo docker compose exec kong kong reload
echo "✅  Kong reloaded"

echo ""
echo "── Verifying routes via local admin API ──"
sleep 2
echo "Routes configured:"
curl -s http://127.0.0.1:8001/routes | python3 -c "
import json,sys
r=json.load(sys.stdin)
for route in r['data']:
  print(f'  {route[\"name\"]:30s} → paths: {route[\"paths\"]}')
" 2>/dev/null || echo "(admin API output parsing failed, that's OK)"
KONGSH

echo ""
echo "🔍  Running remote smoke tests…"
echo ""

run_check () {
  local label="$1" url="$2" expected="$3"
  local code
  code=$(curl -sk -o /dev/null -w "%{http_code}" "$url")
  if [ "$code" = "$expected" ]; then
    echo "  ✅  $label → HTTP $code (expected $expected)"
  else
    echo "  ❌  $label → HTTP $code (expected $expected)"
    FAILED=1
  fi
}

FAILED=0

run_check "/joke/any"        "https://${KONG_IP}/joke/any"        "200"
run_check "/joke-ui"         "https://${KONG_IP}/joke-ui"         "200"
run_check "/submit (GET)"    "https://${KONG_IP}/submit"          "200"
run_check "/types"           "https://${KONG_IP}/types"           "200"
run_check "/moderate-ui"     "https://${KONG_IP}/moderate-ui"     "200"
run_check "/docs"            "https://${KONG_IP}/docs"            "301"  # Kong → Express redirect
run_check "/mq-admin/"       "https://${KONG_IP}/mq-admin/"       "200"
run_check "/etl-health"      "https://${KONG_IP}/etl-health"      "200"
run_check "rate-limit header" "" ""  # skip

echo ""
echo "── Rate-limit scope test: /joke-ui should NOT be rate-limited ──"
# Exhaust the rate limit on /joke/any ...
echo " Sending 6 rapid requests to /joke/any to exhaust rate limit…"
for i in $(seq 1 6); do
  curl -sk -o /dev/null "https://${KONG_IP}/joke/any" || true
done
# Now check /joke-ui — should still return 200
JOKEUICODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://${KONG_IP}/joke-ui")
if [ "$JOKEUICODE" = "200" ]; then
  echo "  ✅  /joke-ui → HTTP 200 after rate limit exhausted (fix working)"
else
  echo "  ❌  /joke-ui → HTTP $JOKEUICODE after rate limit exhausted (rate limit still leaking to frontend)"
  FAILED=1
fi

echo ""
if [ "$FAILED" -eq 0 ]; then
  echo "✅  All route checks PASSED. Kong redeploy complete."
else
  echo "❌  Some route checks FAILED. Review logs:"
  echo "    ssh -i ~/.ssh/co3404_key azureuser@${KONG_IP} 'sudo docker compose -f /home/azureuser/kong/*.yml logs --tail=30'"
  exit 1
fi
